spring:
  application:
    name: post-service
  
  data:
    mongodb:
      uri: mongodb+srv://k1ngfuon1verse_db_user:Qp65VIy46tPoKE4H@cluster0.zxtjmdf.mongodb.net/citizenportal?retryWrites=true&w=majority
  
  rabbitmq:
    host: puffin.rmq2.cloudamqp.com
    port: 5671                   # Note: 5671 for SSL (amqps), 5672 is for non-SSL
    username: pvvycahn
    password: TK7ncXDXeeImSWO-k7AvYuBL-crSEmtL
    virtual-host: pvvycahn       # Important! CloudAMQP requires the vhost (usually same as username)
    ssl:
      enabled: true

server:
  port: ${PORT:8082}

rabbitmq:
  exchange: post.exchange
  queue: post.queue
  routing-key: post.routing.key
  update-queue: post.update.queue
  update-routing-key: post.update.routing.key
  upvote-queue: post.upvote.queue
  upvote-routing-key: post.upvote.routing.key

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html