export const list = ["Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam", "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "New Delhi",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"]

export const citylist = {
    "Andaman and Nicobar Islands": ["Andaman and Nicobar Islands"],
    "Andhra Pradesh": ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Kakinada","Rajahmundry","Kadapa","Mangalagiri-Tadepalli","Tirupati","Anantapuram","Vizianagaram","Eluru","Nandyal","Ongole","Adoni","Madanapalle","Machilipatnam","Tenali","Proddatur","Chittoor","Hindupur","Srikakulam","	Bhimavaram","Tadepalligudem","Guntakal","Dharmavaram","Gudivada","Narasaraopet","Kadiri","Tadipatri","Chilakaluripet"],
    "Arunachal Pradesh": ["Anjaw","Changlang","Dibang Valley","East Kameng","East Siang","Kurung Kumey","Lohit","Lower Dibang Valley","Lower Subansiri","Papum Pare","Tawang","Tirap","Upper Siang","Upper Subansiri","West Kameng","West Siang"],
    "Assam": ["Guwahati","Silchar","Dibrugarh","Jorhat","Bongaigaon","Tinsukia","Tezpur"],
    "Bihar": ["Patna","Gaya","Bhagalpur","Muzaffarpur","Bihar Sharif","Darbhanga","Purnia","Sasaram","Arrah","Samastipur","Madhubani","Siwan","Chhapra","Munger","Saharsa","Motihari","Bettiah","Begusarai","Katihar"],
    "Chandigarh": ["Chandigarh"],
    "Chhattisgarh": ["Raipur","Bhilai","Bilaspur","Korba","Raj Nandgaon","Raigarh","Jagdalpur","	Ambikapur","Dhamtari","Chirmiri","Bhatapara","Mahasamund","Dalli-Rajhara","Kawardha","Champa","Naila Janjgir","Kanker","Dongragarh","Tilda Neora","Mungeli","Manendragarh","Kondagaon","Gobranawapara","Bemetara","Baikunthpur"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Dadra and Nagar Haveli and Daman and Diu"],
    "Goa": ["Bicholim","Canacona","Cuncolim","Curchorem","Mapusa","Margao","Mormugao","Panaji","Pernem","Ponda","Quepem","Sanguem","Sanquelim","Valpoi"],
    "Gujarat": ["Surat","Ahmedabad","Vadodara","Rajkot","Bhavnagar","Jamnagar","Gandhinagar","Junagadh","Gandhidham","Anand","Navsari","Morbi","Nadiad","Surendranagar","Bharuch","Mehsana","Bhuj","	Porbandar","Palanpur","Valsad","Vapi","Gondal","Veraval","Godhra","Patan","Kalol","Botad","Amreli","Deesa","Jetpur"],
    "Haryana" : ["Faridabad","Gurugram","Panipat","Ambala","Yamunanagar","Rohtak","Hisar","Karnal","Sonipat","Panchkula","Sirsa","Bhiwani","Bahadurgarh","Jind","Thanesar","Kaithal","Rewari","	Palwal","Hansi","	Narnaul"],
    "Himachal Pradesh" : ["Bilaspur","Chamba","Hamirpur","Kangra","Kinnaur","Kullu","Lahul & Spiti","Mandi","Shimla","Sirmaur","Solan","Una"],
    "Jammu and Kashmir":["Anantnag","Badgam","Bandipore","Baramula","Doda","Ganderbal","Jammu","Kathua","Kishtwar","Kulgam","Kupwara","Pulwama","Punch","Rajouri","Ramban","Reasi","Samba","Shupiyan","Srinagar","Udhampur"],
    "Jharkhand":["Bokaro","Chatra","Deoghar","Dhanbad","Dumka","Garhwa","Giridih","Godda","Gumla","Hazaribagh","Jamtara","Khunti","Kodarma","Latehar","Lohardaga","Pakur","Palamu","Pashchimi Singhbhum(West Singhbhum)","Purbi Singhbhum (East Singhbhum)","Ramgarh","Ranchi","Sahibganj","Saraikela-Kharsawan","Simdega"],

}

export const deptlist = ['Municipal Cooperation','CyberSecurity Department','Electricity Department']